### ISSUE TITLE
TileMolester does not run in  maven container UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Skeeve** [toruzz/TileMolester#15]
I'm trying to compile and run TileMolester inside a Maven container, but it fails with "UnsatisfiedLinkError"

```text
Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/java/openjdk/lib/libawt_xawt.so: libXext.so.6: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:259)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:249)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
	at java.base/java.lang.System.loadLibrary(System.java:2063)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1384)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1382)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1381)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1419)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1393)
	at java.desktop/java.awt.Component.<clinit>(Component.java:624)
	at tm.TileMolester.<init>(TileMolester.java:72)
	at tm.TileMolester.main(TileMolester.java:84)
```

Here is what I do:

```bash
docker run -it -v $PWD:/src maven /bin/bash
export DISPLAY=host.docker-internal:0.0
cd /src
./configure.sh
# Here I get some warnings.
./run.sh
# Errors see above
```

**Comment by Skeeve** [comment]
Okay… It's X11 related. In the container, there is no X11 server present.
